jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Créer le dossier data
        run: mkdir -p data  

      - name: Générer le fichier JSON de présence
        run: echo '{}' > data/presences.json

      - name: Afficher les fichiers créés
        run: ls -lah data  

      - name: Commit et push des présences
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add data/presences.json
          git commit -m "Mise à jour des présences"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}